name: Unit tests

on: [push, pull_request]

jobs:
  unit-test:
    name: Unit tests with Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      CITIZEN_DB_DIR: ./data
      CITIZEN_STORAGE: file
      CITIZEN_STORAGE_PATH: /tmp/citizen
      CITIZEN_ADDR: http://127.0.0.1:3000
      CITIZEN_MOCK_ENABLED: true
      CITIZEN_AWS_S3_BUCKET: kr.ne.outsider.test
      AWS_ACCESS_KEY_ID: ooooo
      AWS_SECRET_ACCESS_KEY: xxxxx
      DEBUG: '*,-mocha:*,-express:*,-nock.*,-pouchdb:*,-eslint:*,-eslint*,-snapdragon:*,-body-parser:*,-morgan,-superagent'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: |
            - ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }} }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - run: npm ci
      - run: npm run test:unit -- --forbid-only
